name: CI/CD with Gradle and Docker

on:
  push:
    branches: [ "main" ]

# 테스트 결과 작성을 위해 쓰기권한 추가
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clear Gradle Cache
        run: |
          echo "Deleting Gradle cache..."
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper
          echo "Gradle cache deleted!"

      - name: Set application.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.DB_URL }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}
          spring.jpa.hibernate.ddl-auto: ${{ secrets.DDL_AUTO }}
          jwt.secret: ${{ secrets.JWT_SECRET }}
          jwt.expiration: ${{ secrets.JWT_EXPIRATION }}
          kakao.pay.secret-key: ${{ secrets.KAKAO_PAY_SECRET_KEY }}
          storage.s3.bucket-name: ${{ secrets.S3_BUCKET_NAME }}
          storage.s3.access-key: ${{ secrets.S3_ACCESS_KEY }}
          storage.s3.secret-key: ${{ secrets.S3_SECRET_KEY }}
          storage.s3.region: ${{ secrets.S3_REGION }}
          server.host: ${{ secrets.HOST_URL }}

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build With Gradle
        run: ./gradlew build --no-build-cache --refresh-dependencies -x test

      # build Test
      - name: 테스트 코드 실행
        run: ./gradlew --info test --no-build-cache --refresh-dependencies

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      # 배포 시작
      - name: Docker build & Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sellect-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/sellect-app:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          COMPOSE: "/home/ubuntu/compose/docker-compose.yml"
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: COMPOSE
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker-compose -f $COMPOSE down
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/sellect-app:latest
            sudo docker-compose -f $COMPOSE up -d

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
#          aws-region: ${{ secrets.S3_REGION }}
#
#      - name: Deploy static site to S3 bucket
#        run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME }} --delete